[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "litemind"  # <-- Add the project name here
version = "2025.01.26"
requires-python = ">=3.6"
dependencies = [
    "openai",
    "ollama",
    "anthropic",
    "google-generativeai",
    "pillow",
    "arbol",
    "json-repair",
    "tiktoken",
    "pydantic",
]



# Development dependencies:
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-html",
    "pytest-cov",
    "pytest-md-report",
    "black"
]

# Optional dependencies:
rag = [
    "chromadb"
]
whisper = [
    "openai-whisper"
]
documents = [
    "pymupdf",
    "pymupdf4llm",
]
tables = [
    "pandas",
    "numpy",
    "chardet",
    "tabulate"
]
videos = [
    "ffmpeg-python",
    "imageio[ffmpeg]",
]
embed = [
    "fastembed",
]

# Commands:
[project.scripts]
readmegen = "litemind.tools.readme_generator.readme_generator:main"

# pytest options:
[tool.pytest.ini_options]
log_cli = true