[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "openai",
    "ollama",
    "anthropic",
    "google-generativeai",
    "pillow",
    "ffmpeg-python",
    "arbol",
]

[project.optional-dependencies]
test = [
    "pytest"
]

rag = [
    "chromadb"
]

whisper = [
    "openai-whisper"
]

documents = [
    "pymupdf",
    "pymupdf4llm",
]

tables = [
    "pandas",
    "numpy",
    "chardet",
    "tabulate"
]