[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "openai",
    "ollama",
    "anthropic",
    "google-generativeai",
    "chromadb",
    "pillow",
    "arbol",
]

[project.optional-dependencies]
test = [
    "pytest"
]